apiVersion: v1
kind: Pod
metadata:
  name: php-web
  namespace: php-web
  labels:
    app: php-web
spec:
  containers:
  - image: pier/php-web:1.0
    name: php-web 
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: APP_DB_SRV
      value: "php-db.php-web.svc.cluster.local"
    - name: APP_DB_USER
      value: "sakila"
    - name: APP_DB_PASS
      value: "sakila"
    - name: APP_DB_NAME
      value: "sakila"
