apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: php-web
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32088
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: php-web
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  type: ClusterIP
  selector:
    app: db