apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: php-web
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: registry.candoris.com/npier/php-web:latest
          name: frontend 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"  
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          envFrom:
          - configMapRef:
              name: php-web-config