apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web
  namespace: php-web
  labels:
    app: php-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-web
  template:
    metadata:
      labels:
        app: php-web
    spec:
      containers:
        - image: registry.candoris.com/npier/php-web:latest
          name: php-web 
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"  
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: APP_DB_SRV
              valueFrom:
                configMapKeyRef:
                  name: php-web-config
                  key: app.db.srv
            - name: APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: php-web-config
                  key: app.db.user
            - name: APP_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: php-web-config
                  key: app.db.pass
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: php-web-config
                  key: app.db.name