apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: php-web
spec:
  selector:
    matchLabels:
      app: db # has to match .spec.template.metadata.labels
  serviceName: "db"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mariadb:latest
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"  
        ports:
        - containerPort: 3306
          name: mysql
        envFrom:
        - configMapRef:
            name: php-web-config
        volumeMounts:
        - name: db-schema
          mountPath: /docker-entrypoint-initdb.d
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: "db-schema"
        configMap: 
          name: php-web-schema
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: tanzu
      resources:
        requests:
          storage: 1Gi